import {esc as e,money,time,button,icon,stat,field,option,checkbox} from './ui.mjs';
import {quantityText,quantityInput} from './material-units.mjs';
const table=(headers,rows)=>`<div class="table-wrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="muted">Aucune donnée. Commencez par ajouter vos matières premières.</td></tr>`}</tbody></table></div>`;
export function renderMaterials({state}){
 const all=state.data.materials||[],active=all.filter(m=>m.active),q=state.tableSearch.toLowerCase(),tab=state.materialTab||'materials',recipes=['product','supplement'].flatMap(kind=>state.data.catalog[kind].filter(p=>p.active).map(p=>({...p,kind}))),missing=recipes.filter(p=>!p.recipeConfigured).length;
 let content='';
 if(tab==='materials')content=table(['Matière première','Unité de recette','Stock disponible',''],all.filter(m=>m.name.toLowerCase().includes(q)).map(m=>{return `<tr><td><strong>${e(m.name)}</strong><small>${m.active?'Actif':'Archivé'}</small></td><td>${m.unit==='g'?'Gramme':'Pièce'}</td><td>${quantityText(m.quantity,m.unit)}</td><td><div class="actions">${m.active?button('Achat','material-purchase',m.id,'small primary'):''}${button('Modifier','edit-entity',m.id,'small').replace('data-action=', 'data-kind="material" data-action=')}${m.active?button('Archiver','archive-entity',m.id,'small').replace('data-action=', 'data-kind="material" data-action='):''}</div></td></tr>`;}));
 if(tab==='recipes')content=table(['Produit / supplément','Matières pour une unité vendue',''],recipes.filter(p=>p.name.toLowerCase().includes(q)).map(p=>{return `<tr><td><strong>${e(p.name)}</strong><small>${p.kind==='product'?'Produit':'Supplément'}</small></td><td>${p.recipeConfigured?(p.recipe?.length?p.recipe.map(i=>{const m=all.find(m=>m.id===i.materialId);return `${e(m?.name||'Matière indisponible')} : ${quantityText(i.quantity,m?.unit||'g')}`;}).join('<br>'):'Sans consommation (confirmé)'):'<span class="tag orange">Recette à renseigner</span>'}</td><td>${button('Ajouter matière première liée','material-recipe',p.id,'small primary').replace('data-action=',`data-kind="${p.kind}" data-action=`)}</td></tr>`;}));
 if(tab==='purchases')content=table(['Date','Matière','Quantité achetée','Montant total','Fournisseur','Paiement'],(state.data.materialPurchases||[]).filter(p=>`${p.materialName} ${p.supplierName} ${p.note}`.toLowerCase().includes(q)).map(p=>`<tr><td>${time(p.createdAt)}</td><td>${e(p.materialName)}<small>${e(p.note)}</small></td><td>${quantityText(p.quantity,p.unit)}</td><td>${money(p.amount)}</td><td>${e(p.supplierName||'—')}</td><td>${({cash:'Caisse',bank:'Banque',credit:'Crédit fournisseur'})[p.source]}</td></tr>`));
 return `<div class="page-title"><div><h1>Matières premières consommées</h1><p>Matières, recettes des produits et suppléments, achats et consommation à chaque vente.</p></div><div class="title-actions">${button(icon('plus')+'Matière première','add-entity','material','primary')}${button('Enregistrer un achat','material-purchase','','subtle')}</div></div><div class="stats">${stat('Matières actives',String(active.length),'Grammes ou pièces','box')}${stat('Recettes complètes',String(recipes.length-missing),'Produits et suppléments configurés','check')}${stat('Recettes à compléter',String(missing),'Produits et suppléments actifs','note')}${stat('Matières sans stock',String(active.filter(m=>!m.quantity).length),'Achat requis avant vente','box')}</div><div class="notice">1. Ajoutez les matières. 2. Liez les quantités à chaque produit et supplément. 3. Saisissez les achats (kg, g ou pièces et montant total). Dès qu’une matière est active, chaque vente exige une recette complète et un stock suffisant. La recette vide doit être confirmée pour un article sans consommation.</div><div class="tabs">${[['materials','Matières premières'],['recipes','Recettes produits & suppléments'],['purchases','Achats']].map(([id,n])=>`<button data-action="material-tab" data-id="${id}" class="${tab===id?'active':''}">${n}</button>`).join('')}</div><section class="card table-card"><div class="table-tools"><h3>${tab==='recipes'?'Ajouter matière première liée':tab==='purchases'?'Derniers achats (100)':'Stock matières'}</h3><input id="table-search" type="search" aria-label="Rechercher une matière ou un produit" placeholder="Rechercher…" value="${e(state.tableSearch)}"></div>${content}</section><div class="notice">Les achats créent automatiquement une charge et, si nécessaire, une dette fournisseur. Ne ressaisissez pas la même facture dans Charges. Le coût matière et la marge brute de chaque vente sont conservés puis synchronisés sur le web. La marge brute exclut les autres charges (loyer, salaires…). Une annulation remet les matières en stock à leur coût d’origine.</div>`;
}
export function materialForm(x={}){return `<div class="form-grid">${field('name','Matière première',x.name||'','text','required maxlength="120"')}<div class="field"><label>Unité dans les recettes</label><select name="unit" ${x.id?'disabled':''}>${option('g','Gramme (achats possibles en kg)',x.unit||'g')}${option('piece','Pièce (ex. œuf)',x.unit||'g')}</select>${x.id?`<input type="hidden" name="unit" value="${e(x.unit)}">`:''}</div></div><div class="notice">Exemple : frites et thon en grammes, œufs en pièces. L’unité est conservée pour protéger les recettes et les ventes déjà enregistrées.</div>`;}
export function recipeRow(materials,i={}){const m=materials.find(m=>m.id===i.materialId);return `<div class="recipe-row" data-recipe-row><div class="field"><label>Matière première</label><select name="recipeMaterial" required>${option('','Choisir une matière',i.materialId||'')}${materials.map(m=>option(m.id,m.name+(m.active?'':' (archivée)'),i.materialId||'')).join('')}</select></div><div class="field"><label>Quantité pour 1 unité vendue · <span data-recipe-unit>${m?.unit==='piece'?'pièce(s)':'g'}</span></label><input name="recipeQuantity" inputmode="decimal" required value="${i.quantity?quantityInput(i.quantity):''}" placeholder="Ex. 100"></div><button type="button" class="btn small danger" data-action="recipe-remove" aria-label="Retirer la matière">${icon('trash')}</button></div>`;}
export function recipeForm(entity,materials){return `<div class="notice">Quantités consommées pour <strong>une unité de ${e(entity.name)}</strong>. Exemple : frites 100 g, œuf 1 pièce, thon 70 g. Les matières d’un supplément s’ajoutent à celles du produit.</div><div id="recipe-rows">${(entity.recipe||[]).map(i=>recipeRow(materials,i)).join('')}</div>${button(icon('plus')+'Ajouter matière première liée','recipe-add','','subtle')}<div class="check-list" style="margin-top:18px">${checkbox('emptyRecipe','Cet article ne consomme aucune matière',entity.recipeConfigured&&!entity.recipe?.length)}</div><p class="muted">Une recette validée remplace la précédente pour les prochaines ventes. Les coûts des ventes précédentes restent conservés.</p>`;}
export function purchaseForm(materials,suppliers,id=''){const m=materials.find(m=>m.id===id)||materials[0];return `<div class="form-grid"><div class="field full"><label>Matière première</label><select name="materialId" required>${materials.map(x=>option(x.id,x.name,m?.id)).join('')}</select></div>${field('purchaseQuantity','Quantité achetée','','text','required inputmode="decimal"')}<div class="field"><label>Unité de l’achat</label><select name="purchaseUnit">${purchaseUnits(m)}</select></div>${field('purchaseAmount','Montant total de l’achat (DT)','','text','required inputmode="decimal"')}<div class="field"><label>Paiement</label><select name="source">${option('bank','Banque / hors caisse','bank')}${option('cash','Espèces de la caisse','bank')}${option('credit','Crédit fournisseur','bank')}</select></div><div class="field full"><label>Fournisseur</label><select name="supplierId">${option('','Aucun fournisseur','')}${suppliers.map(x=>option(x.id,x.name,'')).join('')}</select></div></div>${field('note','Référence facture / note (facultatif)','','text','maxlength="300"')}<div class="notice">Ex. thon : 2 kg pour 60.000 DT. La quantité et la valeur entrent en stock, et une charge de 60.000 DT est créée automatiquement. Un paiement caisse exige une session ouverte.</div>`;}
export function purchaseUnits(m){return m?.unit==='piece'?option('piece','Pièce','piece'):option('kg','Kilogramme','kg')+option('g','Gramme','kg');}
