import {esc as e,money,today,time,icon,stat,field} from './ui.mjs';
const root=document.querySelector('#app');let token='',day=today(),report=null,busy=false;
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok){if(response.status===401){token='';login(data.error);}throw new Error(data.error||'Serveur indisponible.');}return data;}
function login(error=''){root.innerHTML=`<main class="auth-page"><section class="auth-card"><div class="brand-mark">S</div><h1>Samurai en ligne</h1><p class="muted">Consultez les résultats synchronisés de vos caisses.</p><form id="login"><div id="error" class="form-error" ${error?'':'hidden'}>${e(error)}</div>${field('password','Mot de passe administrateur','','password','required autocomplete="current-password"')}<button class="btn primary" style="width:100%;margin-top:20px">Se connecter</button></form><p class="muted" style="font-size:12px;margin-top:20px">Les ventes locales apparaissent ici après leur synchronisation.</p></section></main>`;}
function render(){const r=report;root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">S</span><div><strong>samurai</strong><small>TABLEAU DE BORD</small></div></div><div class="nav-label">VOTRE ÉTABLISSEMENT</div><nav><button class="nav-item active">${icon('chart')}Rapport journalier</button></nav><div class="sidebar-bottom"><div class="local-status">Résultats synchronisés</div><small>Samurai POS v0.1.0</small></div></aside><div class="workspace"><header class="topbar"><span>${e(r.company.name)} / Tableau de bord en ligne</span><button class="btn small" id="logout">Se déconnecter</button></header><main class="page-content"><div class="page-title"><div><h1>Votre activité, en ligne</h1><p>Les dernières données reçues de vos postes de caisse.</p></div><div class="title-actions"><input type="date" id="day" aria-label="Date du rapport" value="${day}"><button class="btn primary" id="refresh">${icon('sync')}Actualiser</button></div></div><div id="error" class="form-error" hidden></div><div class="stats">${stat('Chiffre d’affaires net',money(r.total),`${r.count} ventes · ${r.voided} remboursements`)}${stat('Espèces',money(r.cash),'Ventes moins remboursements','wallet')}${stat('Carte & crédit',money(r.card+r.credit),`Carte ${money(r.card)} · Crédit ${money(r.credit)}`,'card')}${stat('Charges',money(r.expensesTotal),'Dépenses du jour','out')}</div><div class="section-grid"><section class="card"><h2>Articles vendus</h2><p class="muted" style="margin-top:10px">Avant remises, remboursements déduits.</p><ul class="report-products">${r.products.map(p=>`<li><div><strong>${e(p.name)}</strong><small>${p.quantity} article(s)</small></div><b>${money(p.total)}</b></li>`).join('')||'<li>Aucune vente synchronisée à cette date.</li>'}</ul></section><section class="card"><h2>Postes connectés</h2><ul class="report-products">${r.devices.map(d=>`<li><div><strong>Poste ${e(d.id.slice(0,8))}</strong><small>Dernier échange : ${time(d.last_seen)}</small></div><span class="tag green">Reçu</span></li>`).join('')||'<li>Aucun poste synchronisé.</li>'}</ul><div class="notice">Les échanges automatiques ont lieu toutes les 5 heures lorsque l’application bureau est ouverte et connectée.</div></section></div><section class="card table-card" style="margin-top:24px"><div class="table-tools"><h3>Tickets du jour</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Ticket / Poste</th><th>Caissier</th><th>Client</th><th>Montant</th><th>Statut</th></tr></thead><tbody>${r.sales.map(s=>`<tr><td>#${String(s.ticket).padStart(5,'0')}<small>${e(s.deviceId.slice(0,8))}</small></td><td>${e(s.userName)}</td><td>${e(s.client?.name||'Client de passage')}</td><td>${money(s.total)}</td><td><span class="tag ${s.voided?'red':'green'}">${s.voided?'Annulé':'Enregistré'}</span></td></tr>`).join('')||'<tr><td colspan="5">Aucun ticket reçu pour cette journée.</td></tr>'}</tbody></table></div></section></main></div></div>`;}
async function load(){report=await api('/admin/report?day='+encodeURIComponent(day));render();}
function errorMessage(error){const box=document.querySelector('#error');if(box){box.hidden=false;box.textContent=error.message;}}
document.addEventListener('submit',async event=>{if(event.target.id!=='login')return;event.preventDefault();if(busy)return;busy=true;const button=event.target.querySelector('button');button.disabled=true;try{const data=await api('/admin/login',{password:new FormData(event.target).get('password')});token=data.token;await load();}catch(error){errorMessage(error);}finally{busy=false;button.disabled=false;}});
document.addEventListener('click',async event=>{const id=event.target.closest('button')?.id;if(id==='logout'){token='';report=null;return login();}if(id==='refresh'){try{await load();}catch(error){errorMessage(error);}}});
document.addEventListener('change',async event=>{if(event.target.id==='day'){day=event.target.value;try{await load();}catch(error){errorMessage(error);}}});
login();
