import {randomUUID} from 'node:crypto';
export class PrintQueue {
  constructor(service,{receiptHtml,closureHtml,printHtml}){Object.assign(this,{service,receiptHtml,closureHtml,printHtml});this.running=false;}
  table(job){return job.kind==='closure'?'closure_print_jobs':'print_jobs';}
  recover(){for(const table of ['print_jobs','closure_print_jobs'])this.service.db.prepare(`UPDATE ${table} SET state='uncertain',error='Interruption pendant l’impression. Vérifiez le papier avant de réimprimer.' WHERE state='printing'`).run();}
  pending(){const db=this.service.db;return [...db.prepare("SELECT *, 'sale' source FROM print_jobs WHERE state='pending'").all(),...db.prepare("SELECT *, 'closure' kind FROM closure_print_jobs WHERE state='pending'").all()].sort((a,b)=>a.created_at.localeCompare(b.created_at))[0];}
  async runJob(job){const s=this.service,table=this.table(job),settings=s.settings();s.db.prepare(`UPDATE ${table} SET state='printing',attempts=attempts+1,error=NULL WHERE id=?`).run(job.id);try{let html;if(job.kind==='closure'){const row=s.db.prepare('SELECT * FROM sessions WHERE id=?').get(job.session_id);if(!row)throw Error('Clôture introuvable.');html=this.closureHtml(s.sessionData(row),settings);}else{const row=s.db.prepare('SELECT * FROM sales WHERE id=?').get(job.sale_id);if(!row)throw Error('Vente introuvable.');html=this.receiptHtml({...JSON.parse(row.data),voidedAt:row.voided_at},job.kind,settings);}await this.printHtml(html,job.kind==='kitchen'?settings.print.kitchenPrinter:settings.print.clientPrinter,job.kind==='client'?settings.print.copies:1);s.db.prepare(`UPDATE ${table} SET state='done' WHERE id=?`).run(job.id);}catch(error){s.db.prepare(`UPDATE ${table} SET state='error',error=? WHERE id=?`).run(error.message,job.id);throw error;}}
  async drain(){if(this.running)return;this.running=true;try{let job;while((job=this.pending())){try{await this.runJob(job);}catch{/* Conserver chaque échec sans bloquer le deuxième ticket. */}}}finally{this.running=false;}}
  async printSale(sale,kind='client'){if(!['client','kitchen'].includes(kind))throw Error('Type de ticket invalide.');if(this.running)throw Error('Impression en cours. Réessayez dans quelques secondes.');const db=this.service.db;let job=db.prepare("SELECT * FROM print_jobs WHERE sale_id=? AND kind=? AND state!='done' ORDER BY created_at LIMIT 1").get(sale.id,kind);if(!job){job={id:randomUUID(),sale_id:sale.id,kind};db.prepare('INSERT INTO print_jobs(id,sale_id,kind,created_at) VALUES (?,?,?,?)').run(job.id,sale.id,kind,new Date().toISOString());}this.running=true;try{await this.runJob(job);return {ok:true};}finally{this.running=false;void this.drain();}}
  async printClosure(session){if(this.running)throw Error('Impression en cours. Réessayez dans quelques secondes.');const db=this.service.db;let job=db.prepare('SELECT * FROM closure_print_jobs WHERE session_id=?').get(session.id);if(!job){job={id:randomUUID(),session_id:session.id};db.prepare('INSERT INTO closure_print_jobs(id,session_id,created_at) VALUES (?,?,?)').run(job.id,session.id,new Date().toISOString());}job.kind='closure';this.running=true;try{await this.runJob(job);return {ok:true};}finally{this.running=false;void this.drain();}}
}
