import { dt } from './money.mjs';
export const escapeHtml = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHtml;
const time=value=>new Intl.DateTimeFormat('fr-TN',{timeZone:'Africa/Tunis',dateStyle:'short',timeStyle:'short'}).format(new Date(value));
export function documentHtml(body,title='Ticket') {
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${e(title)}</title><style>
    @page{size:80mm auto;margin:0}*{box-sizing:border-box}body{width:76mm;margin:0 auto;padding:3mm;font-family:Arial,sans-serif;color:#000;font-size:12px;background:#fff}h1{font-size:21px;margin:3px 0;text-align:center}h2{font-size:17px;text-align:center;margin:7px 0}p{margin:4px 0}.center{text-align:center}.small{font-size:10px}.muted{color:#222}.rule{border-top:1px dashed #000;margin:8px 0}.row{display:flex;justify-content:space-between;gap:8px;padding:3px 0}.row>span:first-child{flex:1}.bold{font-weight:bold}.large{font-size:18px}.option{padding-left:12px;font-size:11px}.comment{padding-left:12px;font-weight:bold;margin:2px 0}.kitchen-note{white-space:pre-wrap;overflow-wrap:anywhere}.logo{display:block;max-width:45mm;max-height:22mm;object-fit:contain;margin:0 auto 5px}footer{text-align:center;margin-top:10px}section{break-inside:avoid}.void{border:2px solid #000;padding:5px;font-weight:bold;text-align:center}@media screen{body{margin:20px auto;border:1px solid #ddd;box-shadow:0 4px 20px #0001}}@media print{body{padding:3mm;margin:0;box-shadow:none;border:0}}
  </style></head><body>${body}</body></html>`;
}
function header(settings) {
  const c=settings.company,p=settings.print;
  return `${p.showLogo&&p.logo?`<img class="logo" src="${e(p.logo)}" alt="Logo">`:''}<h1>${e(c.name)}</h1>${c.address?`<p class="center small">${e(c.address)}</p>`:''}${c.phone?`<p class="center small">${e(c.phone)}</p>`:''}${c.taxId?`<p class="center small">MF : ${e(c.taxId)}</p>`:''}`;
}
export function receiptHtml(sale,kind,settings) {
  const kitchen=kind==='kitchen';const modes={emporter:'À EMPORTER',sur_place:'SUR PLACE',livraison:'LIVRAISON'};
  const items=sale.items.map(item=>`<section><div class="row bold"><span>${item.quantity} × ${e(kitchen?item.kitchenName:item.name)}</span>${kitchen?'':`<span>${dt(item.price*item.quantity)}</span>`}</div>${item.supplements.map(s=>`<div class="row option"><span>↳ ${e(s.name)}${item.quantity>1?` × ${item.quantity}`:''}</span>${kitchen?'':`<span>${dt(s.price*item.quantity)}</span>`}</div>`).join('')}${item.comments.filter(c=>kitchen?settings.print.kitchenComments&&c.kitchen:settings.print.clientComments&&c.client).map(c=>`<p class="comment">→ ${e(c.name)}</p>`).join('')}${kitchen&&item.kitchenNote?`<p class="comment kitchen-note">Note cuisine : ${e(item.kitchenNote)}</p>`:''}</section>`).join('');
  return documentHtml(`${header(settings)}<h2>${kitchen?'BON CUISINE':'TICKET CLIENT'} #${String(sale.displayTicket??sale.ticket).padStart(5,'0')}</h2><p class="center bold">${modes[sale.mode]||'À EMPORTER'}</p>${sale.voidedAt?'<p class="void">VENTE ANNULÉE</p>':''}<p class="small">${time(sale.createdAt)} · ${e(sale.userName)}</p>${settings.print.showClient&&sale.client?`<p>Client : ${e(sale.client.name)}</p>`:''}<div class="rule"></div>${items}${sale.note?`<p class="bold">Note : ${e(sale.note)}</p>`:''}${kitchen?'':`<div class="rule"></div>${sale.discount?`<div class="row"><span>Sous-total</span><span>${dt(sale.subtotal)}</span></div><div class="row"><span>Remise</span><span>− ${dt(sale.discount)}</span></div>`:''}<div class="row bold large"><span>TOTAL</span><span>${dt(sale.total)}</span></div><div class="row"><span>${({cash:'Espèces',card:'Carte',credit:'Crédit client'})[sale.payment]}</span><span>${dt(sale.received)}</span></div>${sale.payment==='cash'?`<div class="row"><span>Monnaie</span><span>${dt(sale.change)}</span></div>`:''}`}<footer class="small">${kitchen?'À préparer':e(settings.company.footer)}<br>Poste ${e(sale.deviceId.slice(0,8))}</footer>`,kind==='kitchen'?'Bon cuisine':'Ticket client');
}
export function closureHtml(session,settings){
  const c=session.summary||{},row=(name,value,bold=false)=>`<div class="row ${bold?'bold':''}"><span>${e(name)}</span><span>${dt(value||0)}</span></div>`;
  return documentHtml(`${header(settings)}<h2>CLÔTURE DE CAISSE</h2><p class="center bold">${e(session.userName)}</p><p class="small">Ouverture : ${time(session.openedAt)}<br>Clôture : ${time(session.closedAt)}</p><p class="small">Référence : ${e(session.id)}</p><div class="rule"></div>${row('Fond de caisse',session.opening)}${row('Ventes espèces',c.cashSales)}${row('Règlements clients espèces',c.clientPayments)}${row('Remboursements espèces',-c.refunds)}${row('Charges de caisse',-c.expenses)}${row('Règlements fournisseurs espèces',-(c.supplierPayments||0))}<div class="rule"></div>${row('Espèces attendues',session.expected,true)}${row('Espèces comptées',session.closing,true)}${row('Écart de caisse',session.variance,true)}<div class="rule"></div>${row('Ventes carte',c.card)}${row('Ventes crédit',c.credit)}${session.reason?`<p class="bold">Observation</p><p>${e(session.reason)}</p>`:''}<footer class="small">Conservez ce justificatif de clôture.</footer>`,'Clôture de caisse');
}
export function reportHtml(report,settings) {
  const row=(name,value,bold=false)=>`<div class="row ${bold?'bold':''}"><span>${e(name)}</span><span>${dt(value)}</span></div>`;
  return documentHtml(`${header(settings)}<h2>RAPPORT DES VENTES</h2><p class="center">${e(report.day)}</p>${report.filters?`<p class="small">${Object.entries(report.filters).filter(([k,v])=>v&&!['from','to'].includes(k)).map(([k,v])=>e(({familyId:'Famille',productId:'Produit',payment:'Paiement',mode:'Service',userId:'Caissier'})[k])+' : '+e(settings.filterNames?.[v]||({cash:'Espèces',card:'Carte',credit:'Crédit',sur_place:'Sur place',emporter:'À emporter',livraison:'Livraison'})[v]||v)).join('<br>')}</p>`:''}<div class="rule"></div>${row('Ventes après remises',report.grossTotal)}${row('Remboursements de la période',report.refundsTotal)}${row('Chiffre d’affaires net',report.total,true)}<p>${report.count} ventes · ${report.voided} annulations</p>${row('Espèces',report.cash)}${row('Carte',report.card)}${row('Crédit',report.credit)}${row('Remises',report.discount)}${row('Charges de la période (toutes)',report.expensesTotal)}${row('Dont charges à crédit',report.creditExpensesTotal||0)}${row('Règlements fournisseurs (hors charges)',report.supplierPaymentsTotal||0)}<div class="rule"></div><p class="bold">ARTICLES NETS (après remises)</p>${report.products.map(p=>`<div class="row small"><span>${p.quantity} × ${e(p.name)}</span><span>${dt(p.total)}</span></div>`).join('')}<div class="rule"></div><p class="bold">CHARGES</p>${report.expenses.map(x=>row(x.description,x.amount)).join('')}${report.sessions.filter(s=>s.closedAt).map(s=>`<div class="rule"></div><p class="bold">Clôture ${e(s.userName)}</p>${row('Espèces attendues',s.expected)}${row('Espèces comptées',s.closing)}${row('Écart',s.variance,true)}`).join('')}<footer class="small">Imprimé le ${time(new Date().toISOString())}</footer>`,'Rapport des ventes');
}
