import {ensure,dayInTunis} from './money.mjs';
const sum=(rows,key)=>rows.reduce((n,x)=>n+(x[key]||0),0);
function date(value){const parsed=new Date(value+'T12:00:00Z');ensure(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(parsed.getTime())&&parsed.toISOString().slice(0,10)===value,'Date invalide.');return value;}
export function reportFilters(args={}){const from=date(args.from||args.day||dayInTunis()),to=date(args.to||args.day||from);ensure(from<=to,'La date de début doit précéder la date de fin.');const filters={from,to,startTime:args.startTime||'',endTime:args.endTime||'',familyId:args.familyId||'',productId:args.productId||'',payment:args.payment||'',mode:args.mode||'',userId:args.userId||''};for(const value of [filters.startTime,filters.endTime])ensure(typeof value==='string'&&(!value||/^([01]\d|2[0-3]):[0-5]\d$/.test(value)),'Heure invalide (format HH:mm).');ensure(!filters.payment||['cash','card','credit'].includes(filters.payment),'Paiement invalide.');ensure(!filters.mode||['sur_place','emporter','livraison'].includes(filters.mode),'Mode invalide.');return filters;}
const clockFormatter=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Tunis',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
export function clockInTunis(value){const parsed=new Date(value);return value&&Number.isFinite(parsed.getTime())?clockFormatter.format(parsed):'';}
// La plage horaire est répétée pour chaque date, bornes incluses à la minute.
// Une plage 22:00–02:00 couvre le matin et le soir des dates sélectionnées.
export function inReportPeriod(filters,day,timestamp){
  if(!day||day<filters.from||day>filters.to)return false;
  if(!filters.startTime&&!filters.endTime)return true;
  const clock=clockInTunis(timestamp);if(!clock)return false;
  const start=filters.startTime||'00:00',end=filters.endTime||'23:59';
  return start<=end?clock>=start&&clock<=end:clock>=start||clock<=end;
}
// Répartir chaque remise en millimes, sans perdre un millime dans les filtres.
export function saleLines(sale){const lines=sale.items.map((item,index)=>{const numerator=BigInt(item.total)*BigInt(sale.discount),denominator=BigInt(sale.subtotal||1);return {...item,discount:Number(numerator/denominator),remainder:Number(numerator%denominator),index};});let rest=sale.discount-sum(lines,'discount');for(const line of [...lines].sort((a,b)=>b.remainder-a.remainder||a.index-b.index)){if(rest--<=0)break;line.discount++;}return lines.map(({remainder,index,...line})=>({...line,net:line.total-line.discount}));}
export function buildReport({sales,refunds,expenses=[],sessions=[],clientPayments=[],supplierPayments=[]},args={}){
  const filters=reportFilters(args),inside=(day,timestamp)=>inReportPeriod(filters,day,timestamp);
  const matching=s=>!filters.payment||s.payment===filters.payment;
  const select=s=>{if(!matching(s)||(filters.mode&&s.mode!==filters.mode)||(filters.userId&&s.userId!==filters.userId))return null;const items=saleLines(s).filter(i=>(!filters.familyId||i.familyId===filters.familyId)&&(!filters.productId||i.productId===filters.productId));return items.length?{...s,items,reportTotal:sum(items,'net'),reportDiscount:sum(items,'discount'),reportGross:sum(items,'total')}:null;};
  const selected=sales.filter(s=>inside(s.day,s.createdAt)).map(select).filter(Boolean),returns=refunds.filter(s=>inside(dayInTunis(new Date(s.voidedAt)),s.voidedAt)).map(select).filter(Boolean),charges=expenses.filter(e=>inside(e.day,e.createdAt));
  const products={},families={},daily={};const aggregate=(sale,sign,day)=>{const d=daily[day]||={day,total:0,sales:0,refunds:0};d.total+=sign*sale.reportTotal;sign>0?d.sales++:d.refunds++;for(const item of sale.items){for(const [dict,id,name] of [[products,item.productId,item.name],[families,item.familyId,item.familyName||'Sans famille']]){const p=dict[id]||={id,name,quantity:0,total:0};p.quantity+=sign*item.quantity;p.total+=sign*item.net;}}};
  selected.forEach(s=>aggregate(s,1,s.day));returns.forEach(s=>aggregate(s,-1,dayInTunis(new Date(s.voidedAt))));
  const grossTotal=sum(selected,'reportTotal'),refundsTotal=sum(returns,'reportTotal'),net=method=>sum(selected.filter(s=>s.payment===method),'reportTotal')-sum(returns.filter(s=>s.payment===method),'reportTotal');
  const hourly=Array.from({length:24},(_,hour)=>({hour:String(hour).padStart(2,'0')+':00',sales:0,refunds:0,total:0}));
  for(const [rows,sign] of [[selected,1],[returns,-1]])for(const sale of rows){const clock=clockInTunis(sign===1?sale.createdAt:sale.voidedAt);if(!clock)continue;const bucket=hourly[Number(clock.slice(0,2))];bucket.total+=sign*sale.reportTotal;sign===1?bucket.sales++:bucket.refunds++;}
  const peakHour=hourly.filter(h=>h.sales).sort((a,b)=>b.sales-a.sales||b.total-a.total||a.hour.localeCompare(b.hour))[0]||null;
  const selectedClientPayments=clientPayments.filter(p=>inside(p.day,p.createdAt||p.created_at)),selectedSupplierPayments=supplierPayments.filter(p=>inside(p.day,p.createdAt||p.created_at));
  return {day:filters.from===filters.to?filters.from:filters.from+' → '+filters.to,filters,sales:selected,refunds:returns,expenses:charges,sessions:sessions.filter(s=>(inside(dayInTunis(new Date(s.openedAt)),s.openedAt)||(s.closedAt&&inside(dayInTunis(new Date(s.closedAt)),s.closedAt)))&&(!filters.userId||s.userId===filters.userId)),grossBeforeDiscount:sum(selected,'reportGross'),grossTotal,refundsTotal,total:grossTotal-refundsTotal,cash:net('cash'),card:net('card'),credit:net('credit'),discount:sum(selected,'reportDiscount')-sum(returns,'reportDiscount'),count:selected.length,voided:returns.length,expensesTotal:sum(charges,'amount'),averageTicket:selected.length?Math.round(grossTotal/selected.length):0,quantity:Object.values(products).reduce((n,p)=>n+p.quantity,0),products:Object.values(products).filter(p=>p.quantity||p.total).sort((a,b)=>b.total-a.total),families:Object.values(families).sort((a,b)=>b.total-a.total),daily:Object.values(daily).sort((a,b)=>a.day.localeCompare(b.day)),hourly,peakHour,clientPayments:selectedClientPayments,clientPaymentsTotal:sum(selectedClientPayments,'amount'),supplierPayments:selectedSupplierPayments,supplierPaymentsTotal:sum(selectedSupplierPayments,'amount'),creditExpensesTotal:sum(charges.filter(x=>x.source==='credit'),'amount'),filtered:!!(filters.startTime||filters.endTime||filters.familyId||filters.productId||filters.payment||filters.mode||filters.userId)};
}
