import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {openDatabase} from '../backend/database.mjs';
import {PosService} from '../backend/service.mjs';
import {SyncEngine} from '../backend/sync.mjs';
import {createCloud} from '../backend/cloud.mjs';
import {PostgresCloud} from '../backend/postgres-cloud.mjs';
import {PGlite} from '@electric-sql/pglite';
import {receiptHtml} from '../backend/receipts.mjs';
import {buildReport} from '../backend/reporting.mjs';
import {validateSync} from '../backend/cloud-validation.mjs';
import {materialQuantity,quantityInput,quantityText} from '../frontend/material-units.mjs';

async function fixture({recipes=true,purchases=true}={}){
 const store=openDatabase(':memory:'),s=new PosService(store);await s.call('setup',{name:'Admin',pin:'123456',company:'Mlewi'});const {token}=await s.call('login',{name:'Admin',pin:'123456'}),call=(a,b={})=>s.call(a,b,token),save=(kind,data)=>call('saveEntity',{kind,data});
 const family=await save('family',{name:'Mlewi'}),product=await save('product',{name:'Mlewi omelette thon',price:9000,familyId:family.id}),extra=await save('supplement',{name:'Extra thon',price:2000,productIds:[product.id]}),supplier=await save('supplier',{name:'Épicerie'});
 const fries=await save('material',{name:'Frites',unit:'g'}),egg=await save('material',{name:'Œuf',unit:'piece'}),tuna=await save('material',{name:'Thon',unit:'g'});
 const buy=(m,q,amount,source='bank')=>({requestId:randomUUID(),materialId:m.id,quantity:q,amount,source,supplierId:supplier.id,note:'Facture test'});
 if(recipes){await call('saveRecipe',{kind:'product',id:product.id,ingredients:[{materialId:fries.id,quantity:100000},{materialId:egg.id,quantity:1000},{materialId:tuna.id,quantity:70000}]});await call('saveRecipe',{kind:'supplement',id:extra.id,ingredients:[{materialId:tuna.id,quantity:20000}]});}
 if(purchases){await call('materialPurchase',buy(fries,2000000,12000));await call('materialPurchase',buy(egg,12000,6000));await call('materialPurchase',buy(tuna,2000000,60000,'credit'));}
 await call('openSession',{opening:100000});
 const sale=(quantity=1,supplements=[])=>({requestId:randomUUID(),items:[{productId:product.id,quantity,supplements}],payment:'cash',received:(9000+2000*supplements.length)*quantity,print:false});
 return {store,s,call,save,product,extra,supplier,fries,egg,tuna,buy,sale,token,close:()=>store.db.close()};
}

test('quantités exactes : kg vers grammes, fractions de pièce et validation',()=>{assert.equal(materialQuantity('2','kg'),2000000);assert.equal(materialQuantity('0,125','kg'),125000);assert.equal(materialQuantity('70','g'),70000);assert.equal(materialQuantity('0.5','piece'),500);assert.equal(quantityInput(100000),'100');assert.match(quantityText(70000,'g'),/70 g/);for(const v of ['0','-1','1.0001','NaN','1e3'])assert.throws(()=>materialQuantity(v,'g'));});

test('achats : stock et valeur CUMP, charge automatique unique, caisse et dette fournisseur',async()=>{const f=await fixture();try{assert.equal(f.s.materials.row(f.tuna.id).value_micros,60000*1e6);assert.equal(f.s.supplierBalances()[f.supplier.id],60000);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM expenses').get().n,3);const purchase=f.buy(f.egg,2000,1000,'cash');const a=await f.call('materialPurchase',purchase);assert.equal((await f.call('materialPurchase',purchase)).duplicate,true);assert.equal(f.s.materials.row(f.egg.id).quantity,14000);assert.equal(f.s.cashSummary(f.s.currentSession(f.s.user(f.token)).id).expected,99000);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM expenses').get().n,4);assert.equal(f.store.db.prepare('SELECT id FROM expenses WHERE id=?').get(a.id).id,a.id);await assert.rejects(f.call('materialPurchase',{...purchase,amount:1001}),/autre contenu/);assert.equal(f.store.db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{f.close();}});

test('chaque article vendu garde son coût : recette, supplément, quantité, remise et historique',async()=>{const f=await fixture();try{const request={...f.sale(2,[f.extra.id]),discount:1000};const a=await f.call('sale',request);assert.equal(a.cost,7600);assert.equal(a.items[0].cost,7600);assert.equal(a.items[0].costing.ingredients.length,4);assert.equal(f.s.materials.row(f.tuna.id).quantity,1820000);const r=await f.call('report',{day:a.day});assert.equal(r.costTotal,7600);assert.equal(r.grossMargin,13400);assert.equal(r.products[0].unitCost,3800);assert.equal(r.materials.find(x=>x.id===f.tuna.id).quantity,180000);await f.call('materialPurchase',f.buy(f.tuna,1000000,45000));await f.call('saveRecipe',{kind:'product',id:f.product.id,ingredients:[{materialId:f.tuna.id,quantity:100000}]});await f.call('saveEntity',{kind:'product',id:f.product.id,data:{name:'Nouveau nom',price:9000,familyId:f.product.familyId}});assert.equal(f.s.entity(f.product.id).recipe[0].quantity,100000);assert.equal((await f.call('sale',request)).duplicate,true);assert.equal((await f.call('saleDetails',{id:a.id})).cost,7600);const b=await f.call('sale',f.sale());assert.equal(b.cost,3532);assert.equal(a.items[0].costing.ingredients.find(i=>i.sourceKind==='supplement').cost,1200);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sales').get().n,2);}finally{f.close();}});

test('annulation restitue exactement les quantités et leur valeur historique même après un nouvel achat',async()=>{const f=await fixture();try{const before=f.s.materials.row(f.tuna.id),a=await f.call('sale',f.sale(2,[f.extra.id]));await f.call('materialPurchase',f.buy(f.tuna,1000000,45000));await f.call('voidSale',{id:a.id,reason:'Commande annulée'});const after=f.s.materials.row(f.tuna.id);assert.equal(after.quantity,before.quantity+1000000);assert.equal(after.value_micros,before.value_micros+45000*1e6);assert.equal((await f.call('report',{day:a.day})).costTotal,0);assert.equal((await f.call('report',{day:a.day})).grossMargin,0);await assert.rejects(f.call('voidSale',{id:a.id,reason:'Commande annulée'}),/déjà annulée/);assert.equal(f.s.materials.row(f.tuna.id).quantity,after.quantity);}finally{f.close();}});

test('recettes et achats obligatoires : refus sans effets partiels sur vente, tickets, stock ou synchronisation',async()=>{for(const options of [{recipes:false},{purchases:false}]){const f=await fixture(options);try{const before={ticket:f.store.get('ticket'),outbox:f.store.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,stock:JSON.stringify(f.s.materials.snapshot())};await assert.rejects(f.call('sale',f.sale(1,[f.extra.id])),options.recipes===false?/Recette à renseigner/:/Stock matière insuffisant/);assert.equal(f.store.get('ticket'),before.ticket);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sales').get().n,0);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM outbox').get().n,before.outbox);assert.equal(JSON.stringify(f.s.materials.snapshot()),before.stock);}finally{f.close();}}});

test('recettes vides explicites, unités immuables, matières liées protégées et permission stock',async()=>{const f=await fixture();try{await assert.rejects(f.call('saveRecipe',{id:f.product.id,kind:'product',ingredients:[]}),/Confirmez/);await assert.rejects(f.call('saveRecipe',{id:f.product.id,kind:'product',ingredients:[{materialId:f.tuna.id,quantity:1},{materialId:f.tuna.id,quantity:2}]}),/une fois/);await assert.rejects(f.call('saveEntity',{kind:'material',id:f.tuna.id,data:{name:'Thon',unit:'piece'}}),/unité/);await assert.rejects(f.call('archiveEntity',{kind:'material',id:f.tuna.id}),/recettes/);await f.call('saveRecipe',{id:f.product.id,kind:'product',ingredients:[],emptyConfirmed:true});assert.equal((await f.call('sale',f.sale())).cost,0);await f.call('saveUser',{name:'Catalogue',pin:'987654',permissions:['catalog'],admin:false});const catalogToken=(await f.s.call('login',{name:'Catalogue',pin:'987654'})).token;await assert.rejects(f.s.call('archiveEntity',{id:f.tuna.id},catalogToken),/permission/);await f.call('saveUser',{name:'Caissier',pin:'654321',permissions:['sell'],admin:false});const {token}=await f.s.call('login',{name:'Caissier',pin:'654321'});assert.deepEqual((await f.s.call('bootstrap',{},token)).materials,[]);for(const [action,args] of [['saveRecipe',{id:f.product.id,kind:'product',ingredients:[],emptyConfirmed:true}],['materialPurchase',f.buy(f.tuna,1000,10)],['saveEntity',{kind:'material',data:{name:'Autre',unit:'g'}}]])await assert.rejects(f.s.call(action,args,token),/permission/);}finally{f.close();}});

test('coûts reportés selon date/heure de vente et annulation ; anciennes ventes jamais valorisées à zéro',async()=>{const f=await fixture();try{const a=await f.call('sale',f.sale(2,[f.extra.id]));a.day='2026-10-01';a.createdAt='2026-10-01T11:00:00Z';const refund={...a,voidedAt:'2026-10-02T14:00:00Z'};const r=buildReport({sales:[a],refunds:[refund]}, {from:'2026-10-02',to:'2026-10-02',startTime:'15:00',endTime:'15:00'});assert.equal(r.total,-22000);assert.equal(r.costTotal,-7600);assert.equal(r.grossMargin,-14400);assert.equal(r.materials.find(x=>x.id===f.tuna.id).quantity,-180000);const legacy={...a,items:a.items.map(({cost,costing,knownCost,...i})=>i)};const old=buildReport({sales:[legacy],refunds:[]},{day:a.day});assert.equal(old.costTotal,null);assert.equal(old.grossMargin,null);assert.equal(old.products[0].cost,null);assert.equal(old.uncostedLines,1);const excluded=buildReport({sales:[a],refunds:[]},{day:a.day,startTime:'13:00'});assert.equal(excluded.costTotal,0);}finally{f.close();}});

async function pgPool(){const db=new PGlite();await db.waitReady;let tail=Promise.resolve();const query=async(sql,args)=>{if(!args&&sql.includes(';')){const r=await db.exec(sql);return {rows:r.at(-1)?.rows||[],rowCount:r.at(-1)?.affectedRows||0};}const r=await db.query(sql,args);return {rows:r.rows,rowCount:r.affectedRows??r.rows.length};};return {connect:async()=>{const previous=tail;let release;tail=new Promise(r=>release=r);await previous;return {query,release};},query,on:()=>{},end:()=>db.close()};}
for(const kind of ['SQLite','PostgreSQL'])test(`sync ${kind} : matières, recettes, achats, coûts et reprise réseau sans doublon`,async()=>{const f=await fixture(),cloud=kind==='SQLite'?createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'test-admin-password'}):new PostgresCloud('',{pool:await pgPool()});try{const sale=await f.call('sale',f.sale(2,[f.extra.id]));const settings=f.s.settings();settings.sync={enabled:true,endpoint:'https://test.example',intervalMinutes:20};f.store.put('settings',JSON.stringify(settings));let lose=true;const engine=new SyncEngine(f.s,()=>'x'.repeat(32),async(url,options)=>{const value=await cloud.sync(JSON.parse(options.body));if(lose){lose=false;throw Error('Réponse perdue');}return {ok:true,json:async()=>value};});await assert.rejects(engine.run(),/perdue/);await engine.run();let d=await cloud.dashboard({day:sale.day});assert.equal(d.report.costTotal,7600);assert.equal(d.report.grossMargin,14400);assert.equal(d.materialPurchases.length,3);assert.equal(d.report.expensesTotal,78000);assert.equal(d.supplierBalances[f.supplier.id],60000);assert.equal(d.materials.find(m=>m.materialId===f.tuna.id).quantity,1820000);assert.equal(d.catalog.product[0].recipe.length,3);await f.call('voidSale',{id:sale.id,reason:'Commande annulée'});await engine.run();d=await cloud.dashboard({day:sale.day});assert.equal(d.report.costTotal,0);assert.equal(d.materials.find(m=>m.materialId===f.tuna.id).quantity,2000000);assert.equal(d.report.sales[0].items[0].cost,7600);}finally{f.close();if(kind==='SQLite')cloud.db.close();else await cloud.close();}});

test('coûts et nouvelles unités synchronisés sont vérifiés, stock d’un autre poste refusé',async()=>{const f=await fixture();try{await f.call('sale',f.sale());const events=f.store.db.prepare("SELECT * FROM outbox WHERE state='pending'").all().map(r=>({id:r.id,seq:r.seq,type:r.type,payload:JSON.parse(r.payload)})),body={deviceId:f.store.get('deviceId'),cursor:0,events};validateSync(body);const bad=structuredClone(body);bad.events.find(e=>e.type==='sale').payload.items[0].cost++;assert.throws(()=>validateSync(bad),/Coût de ligne/);const stock=structuredClone(body);stock.events.find(e=>e.type==='materialStock').payload.deviceId=randomUUID();assert.throws(()=>validateSync(stock),/Stock matière/);const entity=structuredClone(body);entity.events.find(e=>e.type==='entity'&&e.payload.kind==='material').payload.data.unit='kg';assert.throws(()=>validateSync(entity),/Unité matière/);}finally{f.close();}});

test('confidentialité : coût et matières ne figurent ni sur ticket client ni sur bon cuisine',async()=>{const f=await fixture();try{const request=f.sale(2,[f.extra.id]);request.items[0].kitchenNote='Bien cuit';const sale=await f.call('sale',request);for(const kind of ['client','kitchen']){const html=receiptHtml(sale,kind,f.s.settings());assert.doesNotMatch(html,/coût|costing|CUMP|marge|7\.600|7,600|Frites|Œuf/i);if(kind==='kitchen')assert.match(html,/Bien cuit/);else assert.doesNotMatch(html,/Bien cuit/);}assert.equal(sale.cost,7600);}finally{f.close();}});

test('stock exact après purge locale, nouveau prix et épuisement ; le coût historique ne change pas',async()=>{const f=await fixture();try{await f.call('saveRecipe',{id:f.product.id,kind:'product',ingredients:[{materialId:f.tuna.id,quantity:70000}]});const first=await f.call('sale',f.sale());const before=f.s.materials.row(f.tuna.id);await f.call('closeSession',{closing:109000});await f.call('clearLocalHistory',{code:'123*456*789*+-'});assert.deepEqual(f.s.materials.row(f.tuna.id),before);assert.equal(f.s.entity(f.product.id).recipe[0].quantity,70000);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM material_purchases').get().n,3);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM expenses').get().n,3);await f.call('materialPurchase',f.buy(f.tuna,70000,3500));await f.call('openSession',{opening:0});await f.call('saveRecipe',{id:f.product.id,kind:'product',ingredients:[{materialId:f.tuna.id,quantity:2000000}]});const last=await f.call('sale',f.sale());assert.equal(last.cost,61400);assert.equal(f.s.materials.row(f.tuna.id).quantity,0);assert.equal(f.s.materials.row(f.tuna.id).value_micros,0);assert.equal(first.cost,2100);}finally{f.close();}});

test('le lot de synchronisation respecte la taille JSON et continue jusqu’à vider la file',async()=>{const f=await fixture();try{const settings=f.s.settings();settings.sync={enabled:true,endpoint:'https://test.example'};f.store.put('settings',JSON.stringify(settings));for(let i=0;i<8;i++)f.s.emit('company',{name:'test',padding:'é'.repeat(150000),index:i});const sizes=[];const engine=new SyncEngine(f.s,()=>'x'.repeat(32),async(url,options)=>{sizes.push(Buffer.byteLength(options.body));const body=JSON.parse(options.body);return {ok:true,json:async()=>({results:body.events.map(e=>({id:e.id,status:'accepted'})),changes:[],cursor:0,hasMore:false})};});await engine.run();assert.ok(sizes.length>=2);assert.ok(sizes.every(n=>n<2000000));assert.equal(f.store.db.prepare("SELECT COUNT(*) n FROM outbox WHERE state='pending'").get().n,0);}finally{f.close();}});
