import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {resolve} from 'node:path';
import {rmSync} from 'node:fs';
import {openDatabase} from '../backend/database.mjs';
import {PosService} from '../backend/service.mjs';
import {createCloud} from '../backend/cloud.mjs';
import {SyncEngine} from '../backend/sync.mjs';
import {closureHtml} from '../backend/receipts.mjs';
async function fixture(file=':memory:'){const store=openDatabase(file),s=new PosService(store);await s.call('setup',{company:'Test',name:'Admin',pin:'123456'});const {token}=await s.call('login',{name:'Admin',pin:'123456'});const call=(action,args={})=>s.call(action,args,token),save=(kind,data)=>call('saveEntity',{kind,data});const family=await save('family',{name:'Chapati'}),product=await save('product',{name:'Chapati',price:7000,familyId:family.id}),supplier=await save('supplier',{name:'Fournisseur test'}),client=await save('client',{name:'Client test',creditLimit:50000}),category=await save('expenseCategory',{name:'Achats'});const sale=(extra={})=>({requestId:randomUUID(),items:[{productId:product.id,quantity:1}],payment:'cash',received:7000,...extra}),charge=(extra={})=>({requestId:randomUUID(),description:'Achat',categoryId:category.id,supplierId:supplier.id,amount:20000,source:'credit',...extra});return {store,s,call,save,token,product,supplier,client,category,sale,charge};}
test('boutons explicites : aucun ticket sans impression, deux tickets avec impression et double clic unique',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const no=f.sale({print:false});await f.call('sale',no);await f.call('sale',no);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM print_jobs').get().n,0);const settings=f.s.settings();settings.print.autoPrint=false;settings.print.kitchen=false;f.store.put('settings',JSON.stringify(settings));const yes=f.sale({print:true});const sale=await f.call('sale',yes);await f.call('sale',yes);assert.deepEqual(f.store.db.prepare('SELECT kind FROM print_jobs WHERE sale_id=? ORDER BY kind').all(sale.id).map(x=>x.kind),['client','kitchen']);await assert.rejects(f.call('sale',{...yes,print:false}),/autre contenu/);await assert.rejects(f.call('sale',f.sale({print:'no'})),/impression invalide/);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sales').get().n,2);assert.equal((await f.call('sessionSummary')).expected,14000);}finally{f.store.db.close();}});
test('charge à crédit et règlement fournisseur : dette, caisse et charge comptée une seule fois',async()=>{const f=await fixture();try{await f.call('openSession',{opening:50000});await assert.rejects(f.call('expense',f.charge({supplierId:''})),/fournisseur/);const args=f.charge();await f.call('expense',args);await f.call('expense',args);assert.equal((await f.call('sessionSummary')).expected,50000);assert.equal(f.s.supplierBalances()[f.supplier.id],20000);await assert.rejects(f.call('archiveEntity',{kind:'supplier',id:f.supplier.id}),/solde/);await f.call('supplierPayment',{requestId:randomUUID(),supplierId:f.supplier.id,amount:6000,method:'cash'});await f.call('supplierPayment',{requestId:randomUUID(),supplierId:f.supplier.id,amount:4000,method:'bank'});assert.equal(f.s.supplierBalances()[f.supplier.id],10000);const cash=await f.call('sessionSummary');assert.equal(cash.supplierPayments,6000);assert.equal(cash.expenses,0);assert.equal(cash.expected,44000);const r=await f.call('report');assert.equal(r.expensesTotal,20000);assert.equal(r.creditExpensesTotal,20000);assert.equal(r.supplierPaymentsTotal,10000);const closed=await f.call('closeSession',{closing:44000});assert.equal(closed.variance,0);const history=await f.call('closures');assert.match(closureHtml(history[0],f.s.settings()),/Règlements fournisseurs espèces/);assert.match(closureHtml(history[0],f.s.settings()),/-6\.000 DT/);await f.call('supplierPayment',{requestId:randomUUID(),supplierId:f.supplier.id,amount:10000,method:'bank'});assert.equal(f.s.supplierBalances()[f.supplier.id],0);}finally{f.store.db.close();}});
test('règlement fournisseur : idempotence, dépassement, permission et session espèces',async()=>{const f=await fixture();try{await f.call('expense',f.charge());const args={requestId:randomUUID(),supplierId:f.supplier.id,amount:5000,method:'bank',note:'Acompte'};const a=await f.call('supplierPayment',args),b=await f.call('supplierPayment',args);assert.equal(a.id,b.id);assert.equal(b.duplicate,true);assert.equal(f.s.supplierBalances()[f.supplier.id],15000);for(const change of [{amount:6000},{note:'Autre'},{method:'cash'}])await assert.rejects(f.call('supplierPayment',{...args,...change}),/déjà utilisée/);await assert.rejects(f.call('supplierPayment',{...args,requestId:randomUUID(),amount:16000}),/dépasse/);await assert.rejects(f.call('supplierPayment',{...args,requestId:randomUUID(),method:'cash'}),/Ouvrez/);await f.call('saveUser',{name:'Charges',pin:'654321',permissions:['expenses'],active:true,admin:false});const {token}=await f.s.call('login',{name:'Charges',pin:'654321'});await assert.rejects(f.s.call('supplierPayment',{...args,requestId:randomUUID()},token),/permission/);assert.equal((await f.call('bootstrap')).supplierPayments.length,1);}finally{f.store.db.close();}});
test('règlements clients : historique affichable et solde après paiement partiel',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});await f.call('sale',f.sale({payment:'credit',clientId:f.client.id,print:false}));await f.call('clientPayment',{requestId:randomUUID(),clientId:f.client.id,amount:2000,method:'cash'});const b=await f.call('bootstrap');assert.equal(b.clientBalances[f.client.id],5000);assert.equal(b.clientPayments.length,1);assert.equal(b.clientPayments[0].clientName,'Client test');assert.equal(b.clientPayments[0].userName,'Admin');assert.equal(b.cash.expected,2000);}finally{f.store.db.close();}});
test('dettes et règlements conservés après redémarrage et synchronisés sans doublon',async()=>{const file=resolve('data','test',randomUUID()+'.sqlite'),f=await fixture(file),cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});let reopened;try{await f.call('expense',f.charge());const args={requestId:randomUUID(),supplierId:f.supplier.id,amount:5000,method:'bank'};await f.call('supplierPayment',args);const settings=f.s.settings();settings.sync={enabled:true,endpoint:'http://localhost:3256'};f.store.put('settings',JSON.stringify(settings));const sync=new SyncEngine(f.s,()=>'x'.repeat(32),async(url,options)=>({ok:true,json:async()=>cloud.sync(JSON.parse(options.body))}));await sync.run();await sync.run();assert.equal(cloud.db.prepare("SELECT COUNT(*) n FROM records WHERE type='supplierPayment'").get().n,1);f.store.db.close();reopened=openDatabase(file);const service=new PosService(reopened),login=await service.call('login',{name:'Admin',pin:'123456'});const b=await service.call('bootstrap',{},login.token);assert.equal(b.supplierBalances[f.supplier.id],15000);assert.equal(b.supplierPayments.length,1);assert.equal((await service.call('supplierPayment',args,login.token)).duplicate,true);}finally{(reopened||f.store).db.close();cloud.db.close();for(const suffix of ['','-wal','-shm'])rmSync(file+suffix,{force:true});}});
