import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {resolve} from 'node:path';
import {mkdirSync,rmSync} from 'node:fs';
import {openDatabase} from '../backend/database.mjs';
import {PosService,PERMISSIONS} from '../backend/service.mjs';
import {SyncEngine} from '../backend/sync.mjs';
import {createCloud} from '../backend/cloud.mjs';
import {receiptHtml,reportHtml} from '../backend/receipts.mjs';
import {dayInTunis} from '../backend/money.mjs';
import {millimes} from '../frontend/ui.mjs';
import {productPage,PRODUCTS_PER_PAGE} from '../frontend/pagination.mjs';

test('douze produits par page, dernière page et filtre sur une liste réduite',()=>{const items=Array.from({length:25},(_,id)=>({id}));assert.equal(PRODUCTS_PER_PAGE,12);assert.equal(productPage(items).items.length,12);assert.equal(productPage(items,1).items[0].id,12);assert.equal(productPage(items,2).items.length,1);assert.equal(productPage(items.slice(0,4),2).index,0);assert.deepEqual(productPage([],3).items,[]);});
test('déclenchement automatique après cinq heures et reprise limitée à cinq minutes',async()=>{const f=await fixture();try{const settings=f.s.settings();settings.sync.enabled=true;f.store.put('settings',JSON.stringify(settings));const engine=new SyncEngine(f.s,()=>''),timestamp=Date.now();let runs=0;engine.run=async()=>{runs++;};f.store.put('syncLastSuccess',new Date(timestamp-4*3600000).toISOString());await engine.tick();assert.equal(runs,0);f.store.put('syncLastSuccess',new Date(timestamp-5*3600000-1000).toISOString());f.store.put('syncLastAttempt',new Date(timestamp-60000).toISOString());await engine.tick();assert.equal(runs,0);f.store.put('syncLastAttempt',new Date(timestamp-5*60000-1000).toISOString());await engine.tick();assert.equal(runs,1);engine.running=true;await engine.tick();assert.equal(runs,1);}finally{f.store.db.close();}});
test('positions conservées après modification, liste invalide refusée et permission obligatoire',async()=>{const f=await fixture();try{const p=await f.save('product',{name:'Second',price:1000,familyId:f.family.id});await f.call('reorderProducts',{ids:[p.id,f.product.id]});assert.equal(f.s.entities('product')[0].id,p.id);await f.call('saveEntity',{kind:'product',id:p.id,data:{name:'Z dernier alphabétique',price:2000,familyId:f.family.id}});assert.equal(f.s.entities('product')[0].id,p.id);await assert.rejects(f.call('reorderProducts',{ids:[p.id,p.id]}),/liste/);assert.equal(f.s.entities('product')[0].id,p.id);await f.call('saveUser',{name:'Caissier',pin:'654321',permissions:['sell'],active:true,admin:false});const {token}=await f.s.call('login',{name:'Caissier',pin:'654321'});await assert.rejects(f.s.call('reorderProducts',{ids:[f.product.id,p.id]},token),/permission/);const settings=f.s.settings();settings.sync={enabled:true,endpoint:'http://localhost:3256',intervalHours:5};f.store.put('settings',JSON.stringify(settings));const cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});try{const engine=new SyncEngine(f.s,()=>'x'.repeat(32),async(url,options)=>({ok:true,json:async()=>cloud.sync(JSON.parse(options.body))}));await engine.run();assert.equal(JSON.parse(cloud.db.prepare('SELECT data FROM entities WHERE id=?').get(p.id).data).sortOrder,0);}finally{cloud.db.close();}}finally{f.store.db.close();}});
test('rapport en ligne impute les remboursements à leur jour',()=>{const cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});try{const deviceId=randomUUID(),id=randomUUID();cloud.sync({deviceId,cursor:0,events:[{id:randomUUID(),seq:1,type:'sale',payload:{id,deviceId,day:'2026-09-01',total:7000,subtotal:7000,discount:0,payment:'cash',items:[{productId:randomUUID(),name:'Chapati',quantity:1,price:7000,total:7000,supplements:[]}]}},{id:randomUUID(),seq:2,type:'saleVoid',payload:{id,voidedAt:'2026-09-02T12:00:00Z'}}]});assert.equal(cloud.report('2026-09-01').total,7000);assert.equal(cloud.report('2026-09-02').total,-7000);assert.equal(cloud.report('2026-09-02').refundsTotal,7000);}finally{cloud.db.close();}});

async function fixture(path=':memory:'){
  const store=openDatabase(path),s=new PosService(store);await s.call('setup',{name:'Admin',pin:'123456',company:'Samurai'});const {token}=await s.call('login',{name:'admin',pin:'123456'});
  const call=(action,args={})=>s.call(action,args,token);const save=(kind,data)=>call('saveEntity',{kind,data});
  const family=await save('family',{name:'Chapati',color:'#dd9966'}),product=await save('product',{name:'Chapati chawarma',familyId:family.id,price:7000,emoji:'🥙'}),supplement=await save('supplement',{name:'Fromage',price:1000,productIds:[product.id]}),comment=await save('comment',{name:'Sans oignon',productIds:[],client:false,kitchen:true}),category=await save('expenseCategory',{name:'Achats',color:'#7455d9'}),client=await save('client',{name:'Ahmed',creditLimit:30000});
  const saleArgs=(overrides={})=>({requestId:randomUUID(),items:[{productId:product.id,quantity:1,supplements:[supplement.id],comments:[comment.id]}],payment:'cash',received:10000,...overrides});
  return {store,s,token,call,save,family,product,supplement,comment,category,client,saleArgs};
}
test('conversion exacte en millimes et rejet des montants ambigus',()=>{
  assert.equal(millimes('7'),7000);assert.equal(millimes('7,125'),7125);assert.equal(millimes('0.001'),1);assert.equal(millimes('12.5'),12500);
  for(const value of ['-1','1.0001','1e3','NaN','1 000','1,000.000'])assert.throws(()=>millimes(value));
});
test('date commerciale de Tunis autour de minuit',()=>{assert.equal(dayInTunis(new Date('2026-09-25T23:30:00Z')),'2026-09-26');});
test('aucun compte par défaut, codes protégés et limitation des essais',async()=>{
  const f=await fixture();try{const user=f.store.db.prepare('SELECT * FROM users').get();assert.notEqual(user.hash,'123456');assert.equal(user.hash.length,64);assert.equal(user.salt.length,48);await assert.rejects(f.s.call('setup',{name:'other',pin:'123456',company:'x'}));
    for(let i=0;i<5;i++)await assert.rejects(f.s.call('login',{name:'admin',pin:'000000'}));await assert.rejects(f.s.call('login',{name:'admin',pin:'123456'}),/5 minutes/);
  }finally{f.store.db.close();}
});
test('permissions contrôlées dans le moteur et secrets exclus du bootstrap',async()=>{
  const f=await fixture();try{await f.call('saveUser',{name:'Caisse',pin:'987654',permissions:['sell','close'],active:true});const {token}=await f.s.call('login',{name:'caisse',pin:'987654'});
    await assert.rejects(f.s.call('saveEntity',{kind:'family',data:{name:'Fraude'}},token),/permission/);await assert.rejects(f.s.call('report',{},token),/permission/);await assert.rejects(f.s.call('saveSettings',{},token),/permission/);
    const data=await f.s.call('bootstrap',{},token);assert.deepEqual(data.users,[]);assert.equal(JSON.stringify(data).includes('hash'),false);assert.equal(JSON.stringify(data).includes('salt'),false);
  }finally{f.store.db.close();}
});
test('vente sans session refusée et session unique par caissier',async()=>{const f=await fixture();try{await assert.rejects(f.call('sale',f.saleArgs()),/Ouvrez/);await f.call('openSession',{opening:50000});await assert.rejects(f.call('openSession',{opening:0}),/déjà ouverte/);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sessions').get().n,1);}finally{f.store.db.close();}});
test('chapati 7 DT et fromage 1 DT liés, double clic sans double vente',async()=>{
  const f=await fixture();try{await f.call('openSession',{opening:50000});const args=f.saleArgs();const first=await f.call('sale',args),second=await f.call('sale',args);assert.equal(first.total,8000);assert.equal(first.change,2000);assert.equal(first.items[0].supplements[0].name,'Fromage');assert.equal(first.id,second.id);assert.equal(second.duplicate,true);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sales').get().n,1);
    assert.equal(f.store.db.prepare("SELECT COUNT(*) n FROM outbox WHERE type='sale'").get().n,1);await assert.rejects(f.call('sale',{...args,received:20000}),/autre contenu/);assert.equal(f.store.db.prepare('SELECT ticket FROM sales').get().ticket,1);
  }finally{f.store.db.close();}
});
test('quantités, supplément autorisé et remise invalides ne créent aucune vente',async()=>{
  const f=await fixture();try{await f.call('openSession',{opening:0});const other=await f.save('product',{name:'Eau',price:1500,familyId:f.family.id});
    await assert.rejects(f.call('sale',f.saleArgs({items:[{productId:other.id,quantity:1,supplements:[f.supplement.id]}]})),/supplément/);
    for(const quantity of [0,1.5,100,-1])await assert.rejects(f.call('sale',f.saleArgs({items:[{productId:f.product.id,quantity}]})));
    await assert.rejects(f.call('sale',f.saleArgs({discount:3000})),/plafond/);await assert.rejects(f.call('sale',f.saleArgs({received:7000})),/invalide/);
    assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sales').get().n,0);assert.equal(Number(f.store.get('ticket')),0);
  }finally{f.store.db.close();}
});
test('prix des ventes figés après modification du catalogue',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const sale=await f.call('sale',f.saleArgs());await f.call('saveEntity',{kind:'product',id:f.product.id,data:{name:'Nouveau nom',price:9000,familyId:f.family.id}});const old=await f.call('saleDetails',{id:sale.id});assert.equal(old.items[0].name,'Chapati chawarma');assert.equal(old.total,8000);}finally{f.store.db.close();}});
test('suppléments facturés par quantité et remise arrondie en entiers',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const sale=await f.call('sale',f.saleArgs({items:[{productId:f.product.id,quantity:3,supplements:[f.supplement.id]}],discount:1,received:30000}));assert.equal(sale.subtotal,24000);assert.equal(sale.total,23999);assert.equal(sale.change,6001);}finally{f.store.db.close();}});
test('charges, remboursements et règlements entrent dans le comptage exact',async()=>{
  const f=await fixture();try{await f.call('openSession',{opening:50000});const cash=await f.call('sale',f.saleArgs());await f.call('sale',f.saleArgs({payment:'card',received:8000}));await f.call('sale',f.saleArgs({payment:'credit',clientId:f.client.id,received:8000}));
    const expense={requestId:randomUUID(),categoryId:f.category.id,amount:3000,source:'cash',description:'Achat pain'};await f.call('expense',expense);await f.call('expense',expense);await f.call('expense',{...expense,requestId:randomUUID(),amount:2000,source:'bank'});
    const pay={requestId:randomUUID(),clientId:f.client.id,amount:4000,method:'cash'};await f.call('clientPayment',pay);await f.call('clientPayment',pay);
    await f.call('voidSale',{id:cash.id,reason:'Commande annulée'});await assert.rejects(f.call('voidSale',{id:cash.id,reason:'Double remboursement'}),/déjà annulée/);
    const summary=await f.call('sessionSummary');assert.equal(summary.expected,51000);assert.equal(summary.cashSales,8000);assert.equal(summary.refunds,8000);assert.equal(summary.expenses,3000);assert.equal(summary.clientPayments,4000);assert.equal(summary.card,8000);assert.equal(f.s.clientBalances()[f.client.id],4000);
  }finally{f.store.db.close();}
});
test('crédit plafonné et paiements excessifs ou demandes modifiées refusés',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});await assert.rejects(f.call('sale',f.saleArgs({payment:'credit',clientId:''})),/client/);await f.call('sale',f.saleArgs({payment:'credit',clientId:f.client.id,received:8000}));await assert.rejects(f.call('clientPayment',{requestId:randomUUID(),clientId:f.client.id,amount:9000,method:'cash'}),/dépasse/);const p={requestId:randomUUID(),clientId:f.client.id,amount:2000,method:'cash'};await f.call('clientPayment',p);await assert.rejects(f.call('clientPayment',{...p,amount:3000}),/déjà utilisée/);await assert.rejects(f.call('archiveEntity',{kind:'client',id:f.client.id}),/solde/);}finally{f.store.db.close();}});
test('clôture avec écart expliqué, ventes bloquées après fermeture',async()=>{const f=await fixture();try{await f.call('openSession',{opening:50000});await f.call('sale',f.saleArgs());await assert.rejects(f.call('closeSession',{closing:1000}),/Expliquez/);assert.ok(f.s.currentSession(f.s.user(f.token)));const close=await f.call('closeSession',{closing:57000,reason:'Comptage vérifié'});assert.equal(close.variance,-1000);assert.equal(f.s.currentSession(f.s.user(f.token)),null);await assert.rejects(f.call('sale',f.saleArgs()),/Ouvrez/);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sessions WHERE closed_at IS NOT NULL').get().n,1);}finally{f.store.db.close();}});
test('annulation d’un ancien ticket déduite de la nouvelle session',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const sale=await f.call('sale',f.saleArgs());await f.call('closeSession',{closing:8000});await f.call('openSession',{opening:10000});await f.call('voidSale',{id:sale.id,reason:'Retour commande'});assert.equal((await f.call('sessionSummary')).expected,2000);}finally{f.store.db.close();}});
test('rapport conserve les jours passés et comptabilise le remboursement à sa date',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const sale=await f.call('sale',f.saleArgs());const oldDay='2026-09-01';const old={...sale,day:oldDay,createdAt:'2026-09-01T12:00:00Z'};f.store.db.prepare('UPDATE sales SET day=?,created_at=?,data=? WHERE id=?').run(oldDay,old.createdAt,JSON.stringify(old),sale.id);await f.call('voidSale',{id:sale.id,reason:'Retour ancien ticket'});const past=await f.call('report',{day:oldDay}),current=await f.call('report',{day:dayInTunis()});assert.equal(past.total,8000);assert.equal(past.refundsTotal,0);assert.equal(current.total,-8000);assert.equal(current.refundsTotal,8000);}finally{f.store.db.close();}});
test('tickets client/cuisine, flèches et échappement des contenus',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const sale=await f.call('sale',f.saleArgs());const settings=f.s.settings();const client=receiptHtml(sale,'client',settings),kitchen=receiptHtml(sale,'kitchen',settings);assert.match(client,/↳ Fromage/);assert.match(client,/8\.000 DT/);assert.doesNotMatch(client,/Sans oignon/);assert.match(kitchen,/Sans oignon/);assert.doesNotMatch(kitchen,/8\.000 DT/);assert.match(client,/80mm auto/);sale.items[0].name='<script>alert(1)</script>';assert.doesNotMatch(receiptHtml(sale,'client',settings),/<script>/);assert.match(receiptHtml(sale,'client',settings),/&lt;script&gt;/);assert.match(reportHtml(await f.call('report'),settings),/RAPPORT DES VENTES/);}finally{f.store.db.close();}});
test('impression automatique crée deux tâches durables après une seule vente',async()=>{const f=await fixture();try{const settings=f.s.settings();settings.print.autoPrint=true;f.store.put('settings',JSON.stringify(settings));await f.call('openSession',{opening:0});const args=f.saleArgs();await f.call('sale',args);await f.call('sale',args);assert.deepEqual(f.store.db.prepare('SELECT kind,state FROM print_jobs ORDER BY kind').all().map(x=>({...x})),[{kind:'client',state:'pending'},{kind:'kitchen',state:'pending'}]);}finally{f.store.db.close();}});
test('famille utilisée et dernier administrateur protégés',async()=>{const f=await fixture();try{await assert.rejects(f.call('archiveEntity',{kind:'family',id:f.family.id}),/Déplacez/);const admin=f.s.user(f.token);await assert.rejects(f.call('saveUser',{id:admin.id,name:'Admin',permissions:[],active:true,admin:false}),/au moins un/);await assert.rejects(f.call('saveUser',{id:admin.id,name:'Admin',permissions:PERMISSIONS,active:false,admin:true}),/propre compte/);}finally{f.store.db.close();}});
test('redémarrage et réouverture de base conservent tickets, séquences et comptes',async()=>{const dir=resolve('data','test'),file=resolve(dir,`${randomUUID()}.sqlite`);mkdirSync(dir,{recursive:true});const f=await fixture(file);await f.call('openSession',{opening:0});const sale=await f.call('sale',f.saleArgs());f.store.db.close();const store=openDatabase(file),s=new PosService(store);try{const {token}=await s.call('login',{name:'admin',pin:'123456'});assert.equal((await s.call('saleDetails',{id:sale.id},token)).total,8000);assert.equal(Number(store.get('ticket')),1);assert.equal((await s.call('bootstrap',{},token)).catalog.product.length,1);}finally{store.db.close();for(const suffix of ['','-wal','-shm'])rmSync(file+suffix,{force:true});}});
test('réseau perdu : outbox conservée, reprise sans double vente en ligne',async()=>{
  const f=await fixture(),cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});try{
    const settings=f.s.settings();settings.sync={enabled:true,endpoint:'http://127.0.0.1:3256',intervalHours:5};f.store.put('settings',JSON.stringify(settings));await f.call('openSession',{opening:0});await f.call('sale',f.saleArgs());
    const failing=new SyncEngine(f.s,()=>'x'.repeat(32),async()=>{throw new Error('Connexion coupée');});await assert.rejects(failing.run(),/Connexion/);const before=f.store.db.prepare("SELECT COUNT(*) n FROM outbox WHERE state='pending'").get().n;assert.ok(before>0);
    let first=true;const engine=new SyncEngine(f.s,()=>'x'.repeat(32),async(url,options)=>{const result=cloud.sync(JSON.parse(options.body));if(first){first=false;throw new Error('Réponse perdue après validation');}return {ok:true,json:async()=>result};});await assert.rejects(engine.run());assert.equal(cloud.report(dayInTunis()).count,1);await engine.run();assert.equal(cloud.report(dayInTunis()).count,1);assert.equal(f.store.db.prepare("SELECT COUNT(*) n FROM outbox WHERE state='pending'").get().n,0);assert.ok(f.store.get('syncLastSuccess'));
  }finally{f.store.db.close();cloud.db.close();}
});
test('conflit de catalogue visible et résolution locale avec révision distante',async()=>{
  const f=await fixture(),cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});try{
    const settings=f.s.settings();settings.sync={enabled:true,endpoint:'http://127.0.0.1:3256',intervalHours:5};f.store.put('settings',JSON.stringify(settings));const engine=new SyncEngine(f.s,()=>'x'.repeat(32),async(url,options)=>({ok:true,json:async()=>cloud.sync(JSON.parse(options.body))}));await engine.run();
    cloud.sync({deviceId:randomUUID(),cursor:0,events:[{id:randomUUID(),seq:1,type:'entity',payload:{id:f.product.id,kind:'product',data:{...f.product,name:'Prix en ligne',price:9000},active:true,baseRevision:1}}]});
    await f.call('saveEntity',{kind:'product',id:f.product.id,data:{name:'Prix local',price:8000,familyId:f.family.id}});await engine.run();const conflicts=f.store.db.prepare('SELECT * FROM sync_conflicts').all();assert.equal(conflicts.length,1);assert.equal(f.s.entity(f.product.id).name,'Prix local');engine.resolve({id:conflicts[0].id,choice:'local'});await engine.run();assert.equal(JSON.parse(cloud.db.prepare('SELECT data FROM entities WHERE id=?').get(f.product.id).data).name,'Prix local');assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sync_conflicts').get().n,0);
  }finally{f.store.db.close();cloud.db.close();}
});
test('API cloud refuse une clé incorrecte et accepte un échange authentifié',async()=>{
  const cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});await new Promise(resolve=>cloud.server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${cloud.server.address().port}`;
  try{const body=JSON.stringify({deviceId:randomUUID(),cursor:0,events:[]});assert.equal((await fetch(url+'/sync',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer incorrect'},body})).status,401);assert.equal((await fetch(url+'/sync',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+'x'.repeat(32)},body})).status,200);assert.equal((await fetch(url+'/admin/report')).status,401);const login=await fetch(url+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:'admin-test-password'})});const {token}=await login.json();assert.equal((await fetch(url+'/admin/report',{headers:{Authorization:`Bearer ${token}`}})).status,200);}finally{await new Promise(resolve=>cloud.server.close(resolve));cloud.db.close();}
});
