import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {openDatabase} from '../backend/database.mjs';
import {PosService} from '../backend/service.mjs';
import {receiptHtml} from '../backend/receipts.mjs';
import {SyncEngine} from '../backend/sync.mjs';
import {createCloud} from '../backend/cloud.mjs';

async function fixture(){const store=openDatabase(':memory:'),service=new PosService(store);await service.call('setup',{name:'Admin',pin:'123456',company:'Samurai'});const {token}=await service.call('login',{name:'Admin',pin:'123456'}),call=(action,args={})=>service.call(action,args,token);const family=await call('saveEntity',{kind:'family',data:{name:'Repas'}}),product=await call('saveEntity',{kind:'product',data:{name:'Chapati',familyId:family.id,price:7000}}),supplier=await call('saveEntity',{kind:'supplier',data:{name:'Épicerie'}});const sale=(quantity=1)=>({requestId:randomUUID(),items:[{productId:product.id,quantity}],payment:'cash',received:7000*quantity,print:false});return {store,service,call,product,supplier,sale,token};}

test('ticket visible repart à 1 après clôture, identifiant interne reste unique',async()=>{const f=await fixture();try{await f.call('openSession',{opening:0});const a=await f.call('sale',f.sale()),b=await f.call('sale',f.sale());assert.equal(a.displayTicket,1);assert.equal(b.displayTicket,2);assert.match(receiptHtml(b,'client',f.service.settings()),/TICKET CLIENT #00002/);await f.call('closeSession',{closing:14000});await f.call('openSession',{opening:0});const c=await f.call('sale',f.sale());assert.equal(c.displayTicket,1);assert.equal(c.ticket,3);assert.match(receiptHtml(c,'kitchen',f.service.settings()),/BON CUISINE #00001/);assert.equal((await f.call('saleDetails',{id:a.id})).displayTicket,1);assert.equal(f.store.db.prepare('SELECT COUNT(DISTINCT ticket) n FROM sales').get().n,3);}finally{f.store.db.close();}});

test('réception fournisseur, seuil, ventes et annulation gardent le stock exact',async()=>{const f=await fixture();try{await f.call('configureStock',{productId:f.product.id,tracked:true,minQuantity:2});const receive={requestId:randomUUID(),kind:'receipt',productId:f.product.id,supplierId:f.supplier.id,quantity:5,unitCost:3000,note:'Facture 1'};const first=await f.call('stockMovement',receive);assert.equal(first.after,5);assert.equal((await f.call('stockMovement',receive)).duplicate,true);assert.equal(f.service.stockSnapshot()[0].supplierId,f.supplier.id);await assert.rejects(f.call('stockMovement',{...receive,quantity:6}),/autre contenu/);await f.call('openSession',{opening:0});const sale=await f.call('sale',f.sale(3));assert.equal(f.service.stockSnapshot()[0].quantity,2);const ticketBefore=Number(f.store.get('ticket'));await assert.rejects(f.call('sale',f.sale(3)),/Stock insuffisant/);assert.equal(Number(f.store.get('ticket')),ticketBefore);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM sales').get().n,1);await f.call('voidSale',{id:sale.id,reason:'Produit retourné'});assert.equal(f.service.stockSnapshot()[0].quantity,5);await f.call('stockMovement',{requestId:randomUUID(),kind:'adjustment',productId:f.product.id,quantity:-2,note:'Inventaire',unitCost:0});assert.equal(f.service.stockSnapshot()[0].quantity,3);assert.equal(f.store.db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{f.store.db.close();}});

test('stock synchronisé par fournisseur, permissions et stockage local conservé',async()=>{const f=await fixture(),cloud=createCloud({file:':memory:',syncToken:'x'.repeat(32),adminPassword:'admin-test-password'});try{await f.call('configureStock',{productId:f.product.id,tracked:true,minQuantity:1});await f.call('stockMovement',{requestId:randomUUID(),kind:'receipt',productId:f.product.id,supplierId:f.supplier.id,quantity:4,unitCost:2000,note:''});const settings=f.service.settings();settings.sync={enabled:true,endpoint:'http://localhost:3256',intervalMinutes:20};f.store.put('settings',JSON.stringify(settings));const engine=new SyncEngine(f.service,()=>'x'.repeat(32),async(url,options)=>({ok:true,json:async()=>cloud.sync(JSON.parse(options.body))}));await engine.run();assert.equal(cloud.dashboard().stock[0].quantity,4);assert.equal(cloud.dashboard().stock[0].supplierName,'Épicerie');await f.call('saveUser',{name:'Caissier',pin:'654321',permissions:['sell'],admin:false});const cashier=(await f.service.call('login',{name:'Caissier',pin:'654321'})).token;await assert.rejects(f.service.call('configureStock',{productId:f.product.id,minQuantity:0},cashier),/permission/);await f.call('clearLocalHistory',{code:'123*456*789*+-'});assert.equal(f.service.stockSnapshot()[0].quantity,4);assert.equal(cloud.dashboard().stock[0].quantity,4);}finally{f.store.db.close();cloud.db.close();}});
