import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {PostgresCloud} from '../backend/postgres-cloud.mjs';
import {createHandler} from '../api/cloud.js';
import {adminToken,validAdminToken} from '../backend/cloud-auth.mjs';
import {openDatabase} from '../backend/database.mjs';
import {PosService} from '../backend/service.mjs';
import {SyncEngine} from '../backend/sync.mjs';
import {dayInTunis} from '../backend/money.mjs';
async function pool(){const db=new PGlite();await db.waitReady;let tail=Promise.resolve();const query=async(sql,args)=>{if(!args&&sql.includes(';')){const r=await db.exec(sql);return {rows:r.at(-1)?.rows||[],rowCount:r.at(-1)?.affectedRows||0};}const r=await db.query(sql,args);return {rows:r.rows,rowCount:r.affectedRows??r.rows.length};};return {db,connect:async()=>{const previous=tail;let release;tail=new Promise(r=>release=r);await previous;return {query,release};},query,on:()=>{},end:()=>db.close()};}
async function request(handler,path,{method='GET',body,authorization}={}){let value;const req={url:path,method,headers:{'content-type':'application/json',...(authorization?{authorization}:{})},body,socket:{remoteAddress:'127.0.0.1'}};const res={setHeader:()=>{},end:text=>value=JSON.parse(text)};await handler(req,res);return {status:res.statusCode,value};}
const env={DATABASE_URL:'postgresql://test',SYNC_TOKEN:'x'.repeat(32),ADMIN_PASSWORD:'a-safe-test-password'};
test('Vercel : jeton de connexion valide après changement d’instance, altération et expiration refusées',()=>{const t=adminToken('secret',1000);assert.equal(validAdminToken(t,'secret',2000),true);assert.equal(validAdminToken(t,'other',2000),false);assert.equal(validAdminToken(t+'x','secret',2000),false);assert.equal(validAdminToken(t,'secret',3601000),false);});
test('Vercel : configuration manquante et protection des routes, sans exposer les secrets',async()=>{const h=createHandler({env:{},getCloud:()=>{throw Error('Should not connect');}});const r=await request(h,'/health');assert.equal(r.status,503);assert.deepEqual(r.value.missing,['DATABASE_URL','SYNC_TOKEN','ADMIN_PASSWORD']);const configured=createHandler({env,getCloud:()=>{throw Error('Unauthorized DB access');}});assert.equal((await request(configured,'/sync',{method:'POST',body:{}})).status,401);assert.equal((await request(configured,'/admin/data')).status,401);});
test('PostgreSQL : synchronisation réelle de caisse, soldes, clôtures, filtres et replay après perte de réponse',async()=>{
 const p=await pool(),cloud=new PostgresCloud('',{pool:p}),store=openDatabase(':memory:'),s=new PosService(store);
 try{await s.call('setup',{company:'Restaurant test',name:'Admin',pin:'123456'});const {token}=await s.call('login',{name:'Admin',pin:'123456'}),call=(a,b={})=>s.call(a,b,token),save=(kind,data)=>call('saveEntity',{kind,data});const f=await save('family',{name:'Chapati'}),product=await save('product',{name:'Chapati',familyId:f.id,price:7000}),extra=await save('supplement',{name:'Fromage',price:1000,productIds:[product.id]}),client=await save('client',{name:'Ahmed',creditLimit:100000}),supplier=await save('supplier',{name:'Fournisseur'}),category=await save('expenseCategory',{name:'Achats'});
 await call('openSession',{opening:50000});await call('sale',{requestId:randomUUID(),items:[{productId:product.id,quantity:1,supplements:[extra.id]}],payment:'cash',received:8000,print:false});await call('sale',{requestId:randomUUID(),items:[{productId:product.id,quantity:1}],payment:'credit',clientId:client.id,print:false});await call('clientPayment',{requestId:randomUUID(),clientId:client.id,amount:2000,method:'cash'});await call('expense',{requestId:randomUUID(),categoryId:category.id,supplierId:supplier.id,description:'Stock',amount:20000,source:'credit'});await call('supplierPayment',{requestId:randomUUID(),supplierId:supplier.id,amount:6000,method:'cash'});await call('closeSession',{closing:54000});
 const settings=s.settings();settings.sync={enabled:true,endpoint:'https://test.vercel.app',intervalMinutes:20};s.put('settings',JSON.stringify(settings));let lost=true;const engine=new SyncEngine(s,()=>env.SYNC_TOKEN,async(url,options)=>{const value=await cloud.sync(JSON.parse(options.body));if(lost){lost=false;throw Error('Réponse perdue');}return {ok:true,json:async()=>value};});await assert.rejects(engine.run(),/perdue/);await engine.run();
 const day=dayInTunis(),d=await cloud.dashboard({day});assert.equal(d.report.total,15000);assert.equal(d.report.cash,8000);assert.equal(d.report.credit,7000);assert.equal(d.clientBalances[client.id],5000);assert.equal(d.supplierBalances[supplier.id],14000);assert.equal(d.closures.length,1);assert.equal((await cloud.dashboard({day,userId:'other'})).closures.length,0);assert.equal(d.closures[0].expected,54000);assert.equal(d.report.expensesTotal,20000);assert.equal(d.report.supplierPaymentsTotal,6000);assert.equal(d.devices.length,1);assert.equal(d.company.name,'Restaurant test');assert.equal(d.report.sales.find(x=>x.payment==='credit').clientName,'Ahmed');assert.equal((await cloud.dashboard({day,productId:product.id,payment:'cash'})).report.total,8000);
 const newInstance=new PostgresCloud('',{pool:p});assert.equal((await newInstance.dashboard({day})).clientBalances[client.id],5000);assert.equal((await p.query("SELECT COUNT(*)::int AS n FROM pos_records WHERE type='sale'")).rows[0].n,2);
 }finally{store.db.close();await cloud.close();}
});
test('PostgreSQL : conflit de catalogue et rollback complet d’un lot financier incohérent',async()=>{const p=await pool(),c=new PostgresCloud('',{pool:p});try{const deviceId=randomUUID(),id=randomUUID(),event={id:randomUUID(),seq:1,type:'entity',payload:{id,kind:'family',data:{name:'Initial'},active:true,baseRevision:0}},body={deviceId,cursor:0,events:[event]};await c.sync(body);assert.equal((await c.sync(body)).results[0].revision,1);const change={...event,id:randomUUID(),payload:{...event.payload,data:{name:'Concurrent'}}};const conflict=await c.sync({deviceId:randomUUID(),cursor:0,events:[change]});assert.equal(conflict.results[0].status,'conflict');assert.equal(conflict.results[0].remote.data.name,'Initial');const payment={id:randomUUID(),seq:2,type:'clientPayment',payload:{id:randomUUID(),amount:1000,day:dayInTunis()}};await c.sync({deviceId,cursor:0,events:[payment]});const prior=(await p.query('SELECT COUNT(*)::int n FROM pos_receipts')).rows[0].n;await assert.rejects(c.sync({deviceId,cursor:0,events:[{...event,id:randomUUID(),payload:{...event.payload,id:randomUUID()}},{...payment,id:randomUUID(),payload:{...payment.payload,amount:2000}}]}),/écrasé/);assert.equal((await p.query('SELECT COUNT(*)::int n FROM pos_receipts')).rows[0].n,prior);}finally{await c.close();}});
test('Vercel : login limité, token reconnu par une autre fonction et route réécrite compatible',async()=>{const p=await pool(),cloud=new PostgresCloud('',{pool:p}),h=createHandler({env,getCloud:()=>cloud});try{for(let i=0;i<5;i++)assert.equal((await request(h,'/api/cloud?route=admin/login',{method:'POST',body:{password:'bad'}})).status,401);assert.equal((await request(h,'/admin/login',{method:'POST',body:{password:env.ADMIN_PASSWORD}})).status,429);await p.query('DELETE FROM pos_login_attempts');const r=await request(h,'/admin/login',{method:'POST',body:{password:env.ADMIN_PASSWORD}});assert.equal(r.status,200);const another=createHandler({env,getCloud:()=>new PostgresCloud('',{pool:p})});const report=await request(another,'/api/cloud?route=admin/data&from='+dayInTunis(),{authorization:'Bearer '+r.value.token});assert.equal(report.status,200);assert.equal(report.value.report.total,0);assert.equal((await request(h,'/health')).value.storage,'postgresql');}finally{await cloud.close();}});
